### ISSUE TITLE
lemp-docker-advance ไม่ผ่านเพราะ curl เหมือนกัน

### ISSUE THREAD

**Issue by songwutk** [dixonsatit/lemp-docker-tutorial#2]
checking for cURL support... yes, shared
checking for cURL in default path... not found
[91mconfigure: error: Please reinstall the libcurl distribution -
    easy.h should be in <curl-dir>/include/curl/
[0m[31mERROR[0m: Service 'php' failed to build: The command '/bin/sh -c apk upgrade --update && apk --no-cache add     git autoconf file
g++ gcc binutils isl libatomic libc-dev musl-dev make re2c libstdc++ libgcc libcurl binutils-libs mpc1 mpfr3 gmp libgomp coreutils freetype-
dev libjpeg-turbo-dev libltdl libmcrypt-dev libpng-dev openssl-dev libxml2-dev expat-dev icu-dev libmemcached-dev     && docker-php-ext-inst
all iconv mysqli pdo pdo_mysql curl bcmath mcrypt mbstring json xml zip bz2 opcache intl      && docker-php-ext-configure gd --with-freetype
-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install gd     && git clone --branch php7 https://github.com/php-memc
ached-dev/php-memcached /usr/src/php/ext/memcached     && cd /usr/src/php/ext/memcached     && docker-php-ext-configure memcached --disable-
memcached-sasl     && docker-php-ext-install memcached' returned a non-zero code: 1

**Comment by dixonsatit** [comment]
อ้อเป็นที่ libcurl ต้องเพิ่ม curl-dev เดี่ยวอัพเดทให้แพบ

**Comment by dixonsatit** [comment]
pull ล่าสุดได้เลยนะ
